/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Restaurant {

        private String name;
        private long numOfStars;
        private String priceCat;
        private ArrayList<Review> reviewArr;

    public Restaurant(String name, int numOfStars, String priceCat){
        this.name = name;
        this.numOfStars = numOfStars;
        this.priceCat = priceCat;
        this.reviewArr = new ArrayList();
    }

    public void setReviewArr(ArrayList reviewArr) {
        this.reviewArr = reviewArr;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setNumOfStars(int numOfStars) {
        this.numOfStars = numOfStars;
    }

    public void setPriceCat(String priceCat) {
        this.priceCat = priceCat;
    }

    public String getName() {
        return name;
    }

    public long getNumOfStars() {
        return numOfStars;
    }

    public String getPriceCat() {
        return priceCat;
    }

    public ArrayList getReviewArr() {
        return reviewArr;
    }

    public void addReview(Review review){
        int sum = 0;
        reviewArr.add(review);
        for (Review val : reviewArr ){
            sum += val.getStars();
        }
        this.setNumOfStars(sum / reviewArr.size());
    }

    public String toString() {
        return String.format("The Restaurant %s has %d stars with a price category of %s", this.name, this.numOfStars, this.priceCat);
    }
}
