/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void rollTest() {
        Library rollTest = new Library();
        int[] dice = new int[5];
        assertTrue("this length should return 'true'", rollTest.roll(5).size() == dice.length);
    }
    @Test
    public void containsDuplicatesTest(){
        Library containsDuplicatesTest = new Library();
        int[] testArray = {31, 28, 31, 30, 31, 30};
        assertTrue("this method should return 'true'", containsDuplicatesTest.containsDuplicates(testArray) == true);
    }
    @Test
    public void calArrAvgTest(){
        Library calArrAvgTest = new Library();
        int[] testArray = {1, 2, 3, 4};
        float testAvg = 2.5f;
        float resultAvg =  calArrAvgTest.calArrAvg(testArray);
        assertEquals(testAvg,resultAvg, .02f);
    }
    @Test
    public void calMultiArrAvgTest(){
        Library calMultiArrAvgTest = new Library();
        int[][] weeklyMonthTemperatures = {
                {1, 2, 3, 4, 5, 6}, // 3.5
                {7, 8, 9, 10, 11, 12}, //9.5
                {13, 14 ,15, 16, 17, 18}, // 15.5
                {2, 2, 2, 2, 2, 2} // 2
        };
        int[] expectArr = {2,2,2,2,2,2};

        assertArrayEquals(expectArr,calMultiArrAvgTest.calArrAvg(weeklyMonthTemperatures));
    }

}
