/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class RestaurantTest {
    @Test
    public void RestaurantIntanceTest() {
        Restaurant classUnderTest = new Restaurant("McDonalds", 3, "$$$");
        assertEquals("The Restaurant McDonalds has 3 stars with a price category of $$$.", classUnderTest.toString());
    }

    @Test
    public void AddReviewTest(){
        // Created a review for Arby's
        Review review = new Review("This place is horrible", "DevonH", 1);

        // Created Arby's
        Restaurant classUnderTest = new Restaurant("Arby's", 2, "$$");

        // Gave Arby's the review (Arby's now has that review stored inside it
        classUnderTest.addReview(review);


        assertTrue("", classUnderTest.getReviewArr().contains(review));
    }
    @Test
    public void RestaurantStarAvgPerReviewTest(){
        Review review1 = new Review("This place is horrible", "DevonH", 4);
        Review review2 = new Review("This place is horrible", "AnthonyB", 3);
        Review review3 = new Review("This place is horrible", "Jhia", 1);
        Review review4 = new Review("This place is horrible", "Paula", 1);
        Review review5 = new Review("This place is horrible", "Chris", 2);
        Review review6 = new Review("This place is horrible", "Tisha", 1);
        Restaurant classUnderTest1 = new Restaurant("China Wok", 3, "$");
        classUnderTest1.addReview(review1);
        classUnderTest1.addReview(review2);
        classUnderTest1.addReview(review3);
        classUnderTest1.addReview(review4);
        classUnderTest1.addReview(review5);
        classUnderTest1.addReview(review6);
        assertEquals(2, classUnderTest1.getNumOfStars());
    }
}
