/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.Arrays;



public class Library {
    public ArrayList<Integer> roll(int number){
        int rnd = (int) Math.ceil(Math.random() * 6);
        ArrayList<Integer> diceNumbers = new ArrayList<>();
        for(int i = 0; i < number; i++){
            diceNumbers.add(rnd);
        }
        return diceNumbers;
    }

    public boolean containsDuplicates(int[] array){
        boolean prevNumMatch = false ;
        int prevNum = 0;
        Arrays.sort(array);
        for (int i = 0; i < array.length; i++){
            if(array[i] == array[i + 1]){
                prevNumMatch = true;
                break;
            }
        }
        return prevNumMatch;
    }

    public float calArrAvg(int[] array){
        float arrayTotal = 0;
        for (int i = 0;i < array.length; i++){
            arrayTotal += array[i];
        }
        arrayTotal = arrayTotal / array.length;
        return arrayTotal;
    }

    public int[] calArrAvg(int[][] array){
        int arrayAvg = 0;
        int prevAvg = Integer.MAX_VALUE;
        int arrayTotal = 0;
        int arrayLength = 0;
        int[] newArray = {};
        for (int i = 0; i < array.length; i++){
            for (int j = 0; j < array.length; j++){
                arrayTotal += j;
                arrayLength++;
            }

            arrayAvg = arrayTotal / arrayLength;
            if (arrayAvg < prevAvg){
                prevAvg = arrayAvg;
            }
            newArray = array[i];
        }
        return newArray;
    }
}
